name: JavaDeploy

on: [push, pull_request]

jobs:
  buildJar:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew jar -PbuildVersion=${{startsWith(github.ref, 'refs/tags/') && github.ref_name || format('deploy-{0}', github.run_number)}}
        env:
          gh_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload built jar file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}
          path: build/libs/DiscordPlugin.jar
