name: JavaDeploy

on: [push, pull_request]

jobs:
  buildJar:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew jar -Pbuildversion=${RELEASE_VERSION:1}

      - name: Upload built jar file
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/libs/DiscordPlugin.jar
          tag: ${{ github.ref }}
